pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

schedules:
- cron: '*/1 * * * *'
  displayName: Every minute
  branches:
    include:
    - feat/$(env)
  always: true

steps:
- script: |
    echo "Running on branch: $(Build.SourceBranch)"
  displayName: 'Hello world'
