pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

schedules:
- cron: '*/5 * * * *'
  displayName: Every five minutes
  branches:
    include:
    - main
  always: true

steps:
- script: |
    echo "Running on branch: $(Build.SourceBranch)"
  displayName: 'Hello world'
