name: Main pipeline

on: workflow_dispatch

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run:
          tree -R /
